# XRD for connecting to CAPI cluster
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: connections.capi.crossplane.io
spec:
  group: capi.crossplane.io
  names:
    kind: Connection
    plural: connections
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              kubeconfig:
                type: string
                description: Name of secret with CAPI Cluster Kubeconfig.
            required:
            - kubeconfig
