# XRD for Kubernetes cluster provisioned using CAPI
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: cluster.capi.crossplane.io
spec:
  group: capi.crossplane.io
  names:
    kind: Cluster
    plural: clusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              projectId:
                type: string
                description: Equinix Metal Project ID.
            required:
            - projectId
