# Composition for creating Helm release that uses default ProviderConfig
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  name: applications.demo.crossplane.io
  labels:
    plan: full
    provider: helm
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: demo.crossplane.io/v1alpha1
    kind: Applications
  resources:
    - base:
        apiVersion: helm.crossplane.io/v1alpha1
        kind: Release
        spec:
          rollbackLimit: 3
          forProvider:
            namespace: default
            chart:
              name: demo-app
              # need to update this repository link appropriately
              repository: https://charts.crossplane.io
              version: "0.0.1"
            values: {}
      patches:
        # All Helm releases derive their labels and annotations from the XR.
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.version
          toFieldPath: spec.forProvider.chart.version
