# XRD for deploying app into a Kubernetes cluster
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: applications.demo.crossplane.io
spec:
  group: demo.crossplane.io
  names:
    kind: Application
    plural: applications
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                type: string
                description: Application chart version.
              configData:
                type: string
                description: MySQL database config data.
            required:
            - version
            - configData
