# Composition with Equinix Metal Machine
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  name: mysqlinstances.metal.equinix.com
  labels:
    plan: full
    provider: helm
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: mysql.crossplane.io/v1alpha1
    kind: Instance
  resources:
    - base:
        apiVersion: server.metal.equinix.com/v1alpha2
        kind: Device
        spec:
          forProvider:
            hostname: crosscapimetal
            plan: t1.small.x86
            facility: ewr1
            operatingSystem: ubuntu_20_10
            billingCycle: hourly
            hardware_reservation_id: next_available
            locked: false
            tags:
            - crossplane
            - development
            # CustomData is stored as a string, available through the metadata.
            # We can patch this value to keep userdata static.
            customdata: |
              {"user": "crosscapimetal", "password": "cros5-cap1-meta7", "dnsToken": "crosscapimetal"}
            userdata: |
              #!/usr/bin/env bash
              export DEBIAN_FRONTEND=noninteractive
              MD=https://metadata.platformequinix.com/metadata

              # XP-EM stores customdata as string, not structure, so extra jq
              DATA="$(curl -s $MD | jq -r .customdata | jq -r .)"
              T="$(echo "$DATA" | jq -r .dnsToken)"
              U="$(echo "$DATA" | jq -r .user)"
              P="$(echo "$DATA" | jq -r .password)"

              # Get our hostname updated
              curl -k "http://freedns.afraid.org/dynamic/update.php?$T"

              # Prepare config questions
              ROOTPW=$(uuidgen -r)
              echo "MySQL Root: '$ROOTPW'"
              apt update -q
              debconf-set-selections <<< "mysql-server mysql-server/root_password password $ROOTPW"
              debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $ROOTPW"

              # Install MySQL, Listen publicly
              apt install mysql-server -y -q
              sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf
              systemctl restart mysql.service

              # Create requested MySQL super-user
              mysql -u root -p"$ROOTPW" -e "create user '$U'@'%' identified by '$P';  grant all on *.* to '$U';FLUSH PRIVILEGES;"
      patches:
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-machine"
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace

