# App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: hasheddan/cross-capi-metal-demo:latest
        name: demo-app
        ports:
          - containerPort: 8080
