# App Service
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: demo
  labels:
    app: demo
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: demo
  type: LoadBalancer