# Composition with the three sub-XRDs we defined
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  name: compositeclusters.aws.platformref.crossplane.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: aws.platformref.crossplane.io/v1alpha1
    kind: CompositeCluster
  resources:
    - base:
        apiVersion: capi.crossplane.io/v1alpha1
        kind: Cluster
      patches:
        - fromFieldPath: spec.projectId
          toFieldPath: spec.projectId
    - base:
        apiVersion: mysql.crossplane.io/v1alpha1
        kind: Instance
      patches:
      # TODO: pass IP address
        - fromFieldPath: spec.projectId
          toFieldPath: spec.projectId
    - base:
        apiVersion: demo.crossplane.io/v1alpha1
        kind: Application
      patches:
      # TODO: pass IP address
        - fromFieldPath: spec.appVersion
          toFieldPath: spec.version
