apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mysqlapp.demo.metal.equinix.com
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: metal.equinix.com/v1alpha1
    kind: Demo
  resources:
    - base:
        apiVersion: capi.crossplane.io/v1alpha1
        kind: Connection
      patches:
        - fromFieldPath: spec.kubeconfig
          toFieldPath: spec.kubeconfig
    - base:
        apiVersion: mysql.crossplane.io/v1alpha1
        kind: Instance
      patches:
        - fromFieldPath: spec.projectId
          toFieldPath: spec.projectId
        - fromFieldPath: spec.configData
          toFieldPath: spec.configData
    - base:
        apiVersion: demo.crossplane.io/v1alpha1
        kind: Application
      patches:
        - fromFieldPath: spec.appVersion
          toFieldPath: spec.version
        - fromFieldPath: spec.configData
          toFieldPath: spec.configData
