apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: cross-capi-metal
spec:
  crossplane:
    version: ">=v0.1.0-0"
  dependsOn:
    - provider: packet/crossplane-provider-equinix-metal
      version: ">=v0.1.0-0"
    - provider: crossplane/provider-helm
      version: ">=v0.3.0-0"
