# Top-Level XRD
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: demos.metal.equinix.com
spec:
  group: metal.equinix.com
  names:
    kind: Demo
    plural: demos
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                  description: Equinix Metal Project ID.
                configData:
                  type: string
                  description: MySQL database config data.
                appVersion:
                  type: string
                  description: Version of application to deploy.
                kubeconfig:
                  type: string
                  description: Name of secret with CAPI cluster kubeconfig.
              required:
                - projectId
                - appVersion
                - configData
                - kubeconfig
